Feature/mul 288 cli command to generate settlements
BitBagCommerce/OpenMarketplace pull request #125
Opened 2023-11-21 17:16 UTC by beniaminblaszkiewicz

2023-11-28 07:32 UTC, senghe requested changes

2023-11-28 07:32 UTC, senghe commented on spec/Component/Settlement/PeriodStrategy/MonthlySettlementPeriodResolverSpec.php
> +    public function it_support_vendor_when_settlement_frequency_is_monthly(
it support[s]

2023-11-28 07:32 UTC, senghe commented on src/Component/Settlement/Cli/SettlementGenerateCommand.php
> +        return [null, null];
We should throw an exception here

2023-11-28 07:32 UTC, senghe commented on src/Component/Settlement/Resources/services/cli.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
Missing OpenSource header

2023-11-28 07:32 UTC, senghe commented on tests/Integration/Cli/SettlementGenerateCommandTest.php
> +    public function test_it_generates_settlements_for_all_vendors(): void
I see there looks as it's a place for splitting assertions into private methods and reuse them.

2023-11-28 07:32 UTC, senghe commented on tests/Integration/Cli/SettlementGenerateCommandTest.php
> +    private function getLastQuarterStartDate(): int
I saw this method somewhere on the top - how about making it public and use here?

2023-11-28 07:32 UTC, senghe commented on tests/Integration/Repository/SettlementRepositoryTest.php
> +        $this->loadFixturesFromFile('SettlementRepositoryTest/test_it_find_last_settlement_for_vendor.yaml');
it find(s)

2023-11-28 07:32 UTC, senghe commented on tests/Integration/DataFixtures/ORM/SettlementRepositoryTest/test_it_find_last_settlement_for_vendor.yaml
> +  vendor_bruce_settlement_1:
How about having settlement for other vendor too here? The test would filter it out - and that's the check of vendor condition I think.

2023-11-28 09:50 UTC, beniaminblaszkiewicz commented on spec/Component/Settlement/PeriodStrategy/MonthlySettlementPeriodResolverSpec.php
> +    public function it_support_vendor_when_settlement_frequency_is_monthly(
fixed

2023-11-28 09:50 UTC, beniaminblaszkiewicz commented on src/Component/Settlement/Cli/SettlementGenerateCommand.php
> +        return [null, null];
fixed + added test

2023-11-28 09:50 UTC, beniaminblaszkiewicz commented on src/Component/Settlement/Resources/services/cli.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
fixed

2023-11-28 09:51 UTC, beniaminblaszkiewicz commented on tests/Integration/Repository/SettlementRepositoryTest.php
> +        $this->loadFixturesFromFile('SettlementRepositoryTest/test_it_find_last_settlement_for_vendor.yaml');
fixed

2023-11-28 09:51 UTC, beniaminblaszkiewicz commented on tests/Integration/DataFixtures/ORM/SettlementRepositoryTest/test_it_find_last_settlement_for_vendor.yaml
> +  vendor_bruce_settlement_1:
fixed

2023-11-29 08:49 UTC, senghe approved these changes

2023-11-29 08:49 UTC, merged