MUL-288: add settlement grid for vendor
BitBagCommerce/OpenMarketplace pull request #127
Opened 2023-12-01 14:41 UTC by beniaminblaszkiewicz

2023-12-20 12:55 UTC, senghe requested changes

2023-12-20 12:57 UTC, DominikWolos commented on features/vendor/settlements.feature
> +    Then I should not see any accept button
There I meant that you should see any accept button on both accepted and settled

2023-12-20 12:58 UTC, DominikWolos commented on features/vendor/settlements.feature
> +    And I accept first possible settlement
The first when was covered in different scenario, removing misleading assertion

2023-12-20 13:02 UTC, DominikWolos commented on features/vendor/settlements.feature
> +    Then I should see 1 settlements
I feel like this is good enough, don't you think? Kind of self explanatory since we have only one settlement for given period and *heads up* the period is filtered like exact value, maybe we should take in consideration only periods for given settlement frequency, what do you think?

2023-12-20 13:04 UTC, DominikWolos commented on src/Component/Settlement/Sender/SettlementsCreatedEmailSender.php
> +            /**
Yes, it is my comment

2023-12-20 13:06 UTC, DominikWolos commented on src/Component/Settlement/Sender/SettlementsCreatedEmailSender.php
> +            /**
My comment addresses deprecation introduced in sylius mailer and prepares sender for version bump without the need of future changes

2023-12-20 13:11 UTC, DominikWolos commented on templates/Context/Vendor/Inventory/index.html.twig
> +    {{ sylius_grid_render(resources, '@SyliusShop/Grid/_default.html.twig') }}
What I read from commit history is that we were previously using exact copy of default template which was replaced by @beniaminblaszkiewicz, I've also spotted second occurence of usage and also replaced there since we were facing exceptions here after custom template removal.

2024-01-02 19:55 UTC, senghe approved these changes

2024-01-02 19:56 UTC, merged