Feature/mul 148
BitBagCommerce/OpenMarketplace pull request #13
Opened 2022-11-25 12:45 UTC by kiczort

https://bitbag.atlassian.net/browse/MUL-148

2022-11-28 21:35 UTC, senghe requested changes

2022-11-28 21:35 UTC, senghe commented on src/Api/Controller/UploadVendorImageAction.php
> +        $image = $this->vendorImageFactory->createNew();
I think a lot of logic here is not the controller related stuff. It's rather application logic, good for command handlers.

2022-11-28 21:35 UTC, senghe commented on src/Api/EventSubscriber/VendorSlugEventSubscriber.php
> +            empty($vendorSlugAware->getCompanyName())
It's too difficult to read. Could you make the expression better for reading?

2022-11-28 21:35 UTC, senghe commented on src/Resources/config/api_resources/Vendor.xml
> +                <attribute name="path">/shop/vendors/{id}</attribute>
I would use the UUID rather than integer identifier for all endpoints

2022-11-28 21:35 UTC, senghe commented on src/Resources/config/serialization/Vendor.xml
> +            <group>shop:customer:read</group>
what's the difference between `shop:customer` and `shop_account`?

2022-11-28 21:35 UTC, senghe commented on src/Resources/config/services/command_handlers.xml
> +                 id="bit_bag.open_marketplace.api.messenger.command_handler.vendor.register_vendor_handler">
```suggestion
                 id="bitbag.open_marketplace.api.messenger.command_handler.vendor.register_vendor_handler">
```

for all xmls :pray:

2022-11-28 21:35 UTC, senghe commented on src/Resources/config/services/provider.xml
> +            <argument type="service" id="open_marketplace.factory.vendor_factory" />
```suggestion
            <argument type="service" id="open_marketplace.factory.vendor" />
```

The `_factory` suffix is not needed as you have `.factory.` prefix. Could you review all similar occurrences?

2022-11-28 21:35 UTC, senghe commented on tests/Functional/Api/VendorProfileTest.php
> +        $header = $this->getHeaderForLoginShopUser('bruce.wayne@example.com');
> $header = $this->getHeaderForLoginShopUser('bruce.wayne@example.com');

Good :+1:

2022-11-28 21:35 UTC, senghe commented on tests/Functional/Api/VendorProfileTest.php
> +    public function test_it_get_vendor_data_for_shop_user_in_his_vendor_context()
it get**s**

2022-11-28 21:35 UTC, senghe commented on ~/Dev/jwtkeys/private.pem
> +-----BEGIN ENCRYPTED PRIVATE KEY-----
What's the `~/Dev` directory?

2022-12-02 06:18 UTC, maxbeckers reviewed
Thanks for the PR! I just left some hints ... this are more ideas to improve the project, no really FIXME comments. Take a look and see if it's helpful or can be ignored.

2022-12-02 06:18 UTC, maxbeckers commented on src/Api/Messenger/Command/Vendor/UploadVendorImage.php
> +
I think we should always have **one** new line at hte end of the file. Maybe we should check it in the pipeline. Here are a lot of new lines in other classes is the one newline in the end missing in this PR.

2022-12-02 06:18 UTC, maxbeckers commented on src/Api/Security/Voter/VendorImageVoter.php
> +        return true;
Just an idea:
```suggestion
       return null !== $currentVendor && null !== $subjectOwner &&  $currentVendor->getId() === $subjectOwner->getId();
```

2022-12-02 06:18 UTC, maxbeckers commented on tests/Functional/FunctionalTestCase.php
> +        return $this->filesPath . '/' . $fileName;
Don't we need `\DIRECTORY_SEPARATOR` here instead of `'/'` to make the tests working on windows as well?

2022-12-06 09:29 UTC, senghe commented on spec/Api/DataProvider/VendorAccountItemDataProviderSpec.php
> +    public function it_is_initializable()
```suggestion
    public function it_is_initializable(): void
```

2022-12-06 09:39 UTC, senghe commented on src/Api/Security/Voter/VendorImageVoter.php
> +        return true;
@maxbeckers in my opinion the @kiczort code is better in reading :)

2022-12-06 09:47 UTC, senghe approved these changes

2022-12-06 10:22 UTC, maxbeckers commented on src/Api/Security/Voter/VendorImageVoter.php
> +        return true;
Ok, Im fine with that. Im familar with my way ... maybe combine 70-74 to `return $currentVendor->getId() === $subjectOwner->getId();`? But can of course as well be as it is.

2022-12-06 12:00 UTC, maxbeckers approved these changes

2022-12-06 12:01 UTC, maxbeckers commented on src/Api/Messenger/Command/Vendor/UploadVendorImage.php
> +
@senghe should I create a Issue for a codestyle check in the pipeline?

2022-12-07 07:16 UTC, merged