[HOTFIX][MUL-289 refresh payment method fix
BitBagCommerce/OpenMarketplace pull request #130
Opened 2023-12-06 12:39 UTC by DominikWolos

2023-12-06 18:49 UTC, senghe requested changes

2023-12-06 18:49 UTC, senghe commented on features/shop/order.feature
> +  Scenario: Browsing orders history, can see selected shipping method
```suggestion
  Scenario: Browsing orders history, can see selected payment method
```

2023-12-06 18:49 UTC, senghe commented on features/shop/order.feature
> +    Then I should see "Bank transfer"
```suggestion
    Then I should see "Bank transfer" payment method
```

2023-12-06 18:49 UTC, senghe commented on features/shop/order.feature
> +    And I finalize order with payment method "bank_transfer"
When from this place

2023-12-06 18:49 UTC, senghe commented on features/shop/order.feature
> +    And I follow "Show"
```suggestion
    And I follow "Show" button
```

2023-12-06 18:49 UTC, senghe commented on spec/Component/Order/Refresher/PaymentRefresherSpec.php
> +        $secondaryOrder->getTotal()->willReturn(100)->shouldBeCalledOnce();
Please don't mix stubs and mocks :pray:

2023-12-06 18:49 UTC, senghe commented on src/Component/Order/Processor/SplitOrderByVendorProcessor.php
> +            foreach ($orders as $iOrder) {
`$iOrder` us not a good name. I would recommend you:

```suggestion
            $secondaryOrders = [$order, ...$order->getSecondaryOrders()];
            foreach ($secondaryOrders as $secondaryOrder) {
```

2023-12-06 18:49 UTC, senghe commented on src/Component/Order/Processor/SplitOrderByVendorProcessor.php
> +        foreach ($orders as $iOrder) {
Same here. Please don't use $iOrder name

2023-12-06 18:49 UTC, senghe commented on src/Component/Order/Refresher/PaymentRefresher.php
> +        $secondaryOrderPaymentCollection = $secondaryOrder->getPayments();
Just `$orderPayments` should be enough here. The context for this method should be independent from being primary/secondary order in my opinion

2023-12-06 18:49 UTC, senghe commented on src/Component/Order/Refresher/PaymentRefresher.php
> +        $secondaryOrderPayment = $secondaryOrderPaymentCollection->last();
Why last? What if customer paid a part using giftcards, and a part using money?

2023-12-06 18:49 UTC, senghe commented on src/Component/Order/Refresher/PaymentRefresher.php
> +        $secondaryOrderPayment->setAmount($secondaryOrder->getTotal());
It's not exactly correct, as you can have multiple payments in single order.

2023-12-07 06:37 UTC, DominikWolos commented on src/Component/Order/Refresher/PaymentRefresher.php
> +        $secondaryOrderPayment->setAmount($secondaryOrder->getTotal());
AFAIK multiple payments might occur after checkout process completes, but please correct me if I am wrong.

From my point of view - to split (primary) order between orders by vendor (secondary), we need a class that would take care of all changes at all points until checkout completes.

As you've pointed that payments might be multiple throughout Order lifecycle, it seems like we should secure this refresher from performing action on orders, for which we have completed the checkout.

Please let me know what you think.

2023-12-07 10:27 UTC, senghe commented on spec/Component/Order/Refresher/PaymentRefresherSpec.php
> +        $secondaryOrder->getTotal()->willReturn(100)->shouldBeCalledOnce();
```suggestion
        $secondaryOrder->getTotal()->willReturn(100);
```

2023-12-07 10:31 UTC, senghe commented on src/Component/Order/Processor/SplitOrderByVendorProcessor.php
> +        $this->entityManager->flush();
I don't think the flush here is necessary

2023-12-07 10:34 UTC, senghe commented on src/Component/Order/Refresher/PaymentRefresher.php
> +        $secondaryOrderPayment = $secondaryOrderPaymentCollection->last();
Finally I think we can leave the topic of multiple payment methods per order.

2023-12-07 10:36 UTC, senghe commented on src/Component/Order/Refresher/PaymentRefresher.php
> +        $secondaryOrderPaymentCollection = $secondaryOrder->getPayments();
Okay, so please change this to `$secondaryOrderPayments` :pray:

2023-12-07 11:00 UTC, DominikWolos commented on src/Component/Order/Processor/SplitOrderByVendorProcessor.php
> +        $this->entityManager->flush();
After I dug up a bit, this processor is detached from OrderProcessor strategy, its only purpose and usage is in OrderController. Flush happens there via ResourceUpdateHandler. 
Removed flush from processor.

2023-12-19 12:49 UTC, senghe approved these changes
Approve in advance. Please add the OS header into the class, and then - merge :)

2023-12-19 12:49 UTC, senghe commented on tests/Behat/Context/Setup/PaymentMethodContext.php
> +declare(strict_types=1);
Missing OS Header ;)

2023-12-19 13:02 UTC, merged