[WIP][MUL-298] Build fails - Deprecated EntityManager::merge() method
BitBagCommerce/OpenMarketplace pull request #132
Opened 2023-12-07 14:17 UTC by DominikWolos

2023-12-12 10:29 UTC, DominikWolos commented on src/Component/ProductListing/Entity/DraftAttributeValue.php
This approach eliminates bug related to adding attributes to product listing. 
@senghe I assumed that PHPStan was the only purpose of this change, am I correct?

2023-12-12 10:30 UTC, DominikWolos commented on templates/Context/Vendor/DraftAttributes/update.html.twig
Fixes bug preventing from editing attribute

2023-12-13 08:08 UTC, senghe requested changes

2023-12-13 08:08 UTC, senghe commented on features/admin/accepting_product_listing.feature
> +    And there is a product 'green-jeans' for listing
```suggestion
    And there is a product 'green-jeans' attached to the product listing
```

2023-12-13 08:08 UTC, senghe commented on features/admin/accepting_product_listing.feature
> +    And I am on "/admin"
This is the "When" section I think. "When I go to "/admin"

2023-12-13 08:08 UTC, senghe commented on features/admin/accepting_product_listing.feature
> +    And I should not see 'attribute-1' with value 'value-1'
There is no "Then" section. Additionally I see you try to test two things in one test, which is bad idea.

2023-12-13 08:08 UTC, senghe commented on features/vendor/create_product_listing_with_attributes.feature
> +    And I click "Save" button
There is no "Then" section.

2023-12-13 08:08 UTC, senghe commented on src/Component/ProductListing/Entity/DraftAttributeValue.php
> -    public function getAttribute(): ?DraftAttributeInterface
Does the method come from any Sylius' interface? If no, I would not approve this change.

2023-12-13 08:19 UTC, senghe commented on src/Component/ProductListing/Entity/DraftAttributeValue.php
Please leave PHPDoc with /** @return ProductDraftAttributeInterface */

2023-12-13 11:41 UTC, DominikWolos commented on src/Component/ProductListing/Entity/DraftAttributeValue.php
> -    public function getAttribute(): ?DraftAttributeInterface
https://github.com/BitBagCommerce/OpenMarketplace/pull/132#discussion_r1423792196 Related comment

2023-12-13 12:48 UTC, senghe requested changes

2023-12-13 12:48 UTC, senghe commented on features/vendor/create_product_listing.feature
>      Then I should see non unique code error message
```suggestion
    And I should see non unique code error message
```

2023-12-13 12:48 UTC, senghe commented on features/vendor/create_product_listing.feature
> +    Then I click "Save" button
```suggestion
    And I click "Save" button
```

2023-12-13 12:48 UTC, senghe commented on features/vendor/create_product_listing.feature
>      And I fill in "Slug" with "product"
I think from the scenario perspective all the data you set aren't so much important to have specified in the Gherkin scenario. I would call this "And I fill the data with "code0" code which is invalid". The rest of the data can be set implicitely in the behat context, even in this step.

2023-12-13 12:48 UTC, senghe commented on src/Component/ProductListing/Entity/DraftAttributeValue.php
> +            throw new \InvalidArgumentException(
please use `Assert::isInstanceOf` :pray:

2023-12-13 13:14 UTC, DominikWolos commented on features/vendor/create_product_listing.feature
>      And I fill in "Slug" with "product"
Can't we leave it as is since all of this actually presents that product is valid?

2023-12-14 09:28 UTC, DominikWolos commented on features/vendor/create_product_listing.feature
>      And I fill in "Slug" with "product"
Initially wanted to discuss this, fixed

2023-12-14 12:53 UTC, merged