hotfix/MUL-280-server-error-while-creating-new-message-category
BitBagCommerce/OpenMarketplace pull request #133
Opened 2023-12-11 12:19 UTC by Quiet0o

- Add validation rule to prevent add empty message category

2023-12-12 07:48 UTC, DominikWolos reviewed
LGTM

2023-12-13 08:51 UTC, senghe requested changes

2023-12-13 08:51 UTC, senghe commented on src/Component/Messaging/Resources/validation/Category.xml
> +<constraint-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
No OS header exception :)

2023-12-13 08:51 UTC, senghe commented on src/Component/Messaging/Resources/validation/Category.xml
> +            <constraint name="NotBlank"/>
Additionally, please add some behats here :)

2023-12-14 18:42 UTC, senghe requested changes

2023-12-14 18:42 UTC, senghe commented on features/admin/message_categories.feature
> +@message_category
`@messaging` :pray:

2023-12-14 18:42 UTC, senghe commented on tests/Behat/Resources/suites/ui/admin/message_categories.yml
> +                tags: '@message_category&&@ui'
`@messaging` :pray:

2023-12-18 13:15 UTC, senghe requested changes

2023-12-18 13:15 UTC, senghe commented on features/admin/message_categories.feature
> +    And I am on "/admin"
"When" section starts here

2023-12-18 13:15 UTC, senghe commented on tests/Behat/Resources/suites.yml
> +    - suites/start_conversation.yml
Why this changes?

2023-12-18 14:37 UTC, Quiet0o commented on tests/Behat/Resources/suites.yml
> +    - suites/start_conversation.yml
Already fixed it was totally unnecessary change

2023-12-18 19:52 UTC, senghe approved these changes

2023-12-19 12:43 UTC, merged