Fix bug about after remove product listing we still have access to update page
BitBagCommerce/OpenMarketplace pull request #142
Opened 2023-12-19 13:30 UTC by Quiet0o

2023-12-19 19:00 UTC, senghe requested changes

2023-12-21 10:40 UTC, senghe requested changes

2023-12-21 10:40 UTC, senghe commented on features/vendor/editing_removed_product_listing.feature
> +    Given there is 1 product listing created by vendor
This line seems to be not needed, as we don't use this listing anywhere in the test.

2023-12-21 10:40 UTC, senghe commented on features/vendor/editing_removed_product_listing.feature
> +    Given I am on edit page product listing "/en_US/account/vendor/product-listings/edit"
This is "When"

2023-12-21 10:40 UTC, senghe commented on tests/Behat/Page/Vendor/ProductListingInterface.php
> +<?php
Missing OS header

2023-12-21 10:40 UTC, senghe commented on translations/flashes.en.yml
> +        product_listing_removed : 'This product has been deleted.'
```suggestion
        product_listing_removed : 'The product listing you're trying to reach has been deleted.'
```

2023-12-21 10:55 UTC, Quiet0o commented on features/vendor/editing_removed_product_listing.feature
> +    Given there is 1 product listing created by vendor
I need to create product listing because in `ProductListingContext:thereProductListingIsRemoved `i set flag `removed` to true in product listing and without product listing i can't set this flag

2023-12-21 11:11 UTC, senghe commented on features/vendor/editing_removed_product_listing.feature
> +    Given there is 1 product listing created by vendor
So the next line should be like "And the product listing is removed"

2023-12-21 12:58 UTC, senghe requested changes

2023-12-21 12:58 UTC, senghe commented on tests/Behat/Context/Ui/Vendor/ProductListingContext.php
> +        $productListing = $this->sharedStorage->get('product_listing0');
Ii do not get, why it's 'product_listing0' with '0' at the end

2023-12-21 13:04 UTC, Quiet0o commented on translations/flashes.en.yml
> +        product_listing_removed : 'This product has been deleted.'
because when i create one product listing using ` Given there is 1 product listing created by vendor` id in [this](https://github.com/BitBagCommerce/OpenMarketplace/blob/d26e65bc84f0535260557dbed3acc07cdfe330c7/tests/Behat/Context/Ui/Vendor/ProductListingContext.php#L198) is set to 0 and mine function set `setRemoved` flag for only one product listing

2023-12-21 13:05 UTC, Quiet0o commented on tests/Behat/Context/Ui/Vendor/ProductListingContext.php
> +        $productListing = $this->sharedStorage->get('product_listing0');
because when i create one product listing using ` Given there is 1 product listing created by vendor` id in [this](https://github.com/BitBagCommerce/OpenMarketplace/blob/d26e65bc84f0535260557dbed3acc07cdfe330c7/tests/Behat/Context/Ui/Vendor/ProductListingContext.php#L198) is set to 0 and mine function set `setRemoved` flag for only one product listing

2024-01-02 11:55 UTC, senghe commented on tests/Behat/Context/Ui/Vendor/ProductListingContext.php
> +        $productListing = $this->sharedStorage->get('product_listing0');
It shouldn't be called like that. Iterating suffixes in naming is antipattern and we have to avoid this. The next person who will read this code will be confused and will ask same question I asked here :)

2024-01-02 18:06 UTC, senghe approved these changes

2024-01-02 18:07 UTC, merged