[MUL-288] Settlements payout
BitBagCommerce/OpenMarketplace pull request #145
Opened 2023-12-21 08:54 UTC by DominikWolos

2024-01-02 20:26 UTC, senghe commented on src/Component/Core/Common/StateMachine/SettlementStateMachineTransition.php
> +        bool $flush = false
To be honest, I don't get why we need the $flush parameter

2024-01-02 20:27 UTC, senghe requested changes

2024-01-02 20:27 UTC, senghe commented on src/Component/Core/Common/StateMachine/SettlementCallbacks.php
> +    /**
I would also put a special file in `doc/` directory where we would describe all the case.

2024-01-03 06:22 UTC, DominikWolos commented on src/Component/Core/Common/StateMachine/SettlementStateMachineTransition.php
> +        bool $flush = false
I had some idea here, but it probably is worth removing.

2024-01-03 06:22 UTC, DominikWolos commented on src/Component/Core/Common/StateMachine/SettlementCallbacks.php
> +    /**
Will do

2024-01-04 09:47 UTC, senghe requested changes

2024-01-04 09:47 UTC, senghe commented on doc/settlement_state_machine.md
> +### State Machine
The file currently is so technical. I would put there some content as "In order to use a payment gateway you need to handle..." etc.

2024-01-04 12:55 UTC, senghe approved these changes

2024-01-04 12:55 UTC, merged