[MUL-265] Vendor can delete images
BitBagCommerce/OpenMarketplace pull request #147
Opened 2023-12-27 14:29 UTC by Quiet0o

2024-01-02 20:40 UTC, senghe requested changes

2024-01-02 20:40 UTC, senghe commented on features/vendor/vendor_can_remove_product_lisitng_image.feature
> +    Then I should not see image
The scenario should have only one list of Given/When/Then. Here we have two scenarios in one - it needs to be split.

2024-01-02 20:40 UTC, senghe commented on src/Component/ProductListing/Repository/DraftImageRepository.php
> + */
```suggestion
/*
 * This file has been created by developers from BitBag.
 * Feel free to contact us once you face any issues or want to start
 * You can find more information about us on https://bitbag.io and write us
 * an email on hello@bitbag.io.
 */
 
declare(strict_types=1);
```

2024-01-02 20:40 UTC, senghe commented on src/Component/ProductListing/Repository/DraftImageRepositoryInterface.php
> + */
```suggestion
/*
 * This file has been created by developers from BitBag.
 * Feel free to contact us once you face any issues or want to start
 * You can find more information about us on https://bitbag.io and write us
 * an email on hello@bitbag.io.
 */
 
declare(strict_types=1);
```

2024-01-02 20:40 UTC, senghe commented on src/Component/ProductListing/Repository/DraftImageRepository.php
> +    }
There is no need for splitting this into two methods. Additionally, the query should be tested in PHPUnit

2024-01-02 20:40 UTC, senghe commented on features/vendor/vendor_can_remove_product_lisitng_image.feature
> +    Given There is a product listing with code "product-listing-code" and name "product-listing-name" and status "verified" with attribute and image
```suggestion
    Given There is a verified product listing "product-listing-code" named "product-listing-name"
    And the product listing has an attribute
    And the product listing has an image attached
```

2024-01-02 20:40 UTC, senghe commented on src/Component/ProductListing/ListingPersister.php
> +            $entity = $this->entityManager->find(DraftImage::class, $image->getId());
I do not get this line

2024-01-03 13:52 UTC, Quiet0o commented on src/Component/ProductListing/ListingPersister.php
> +            $entity = $this->entityManager->find(DraftImage::class, $image->getId());
It was totally unnecessary line

2024-01-05 07:57 UTC, senghe requested changes

2024-01-05 07:57 UTC, senghe commented on tests/Integration/Repository/DraftImageRepositoryTest.php
> +        self::assertCount(1, $queryBuilder);
```suggestion
        $vendorImages = $this->repository->findVendorDraftImages($draft);

        $this->assertCount(1, $vendorImages);
```

2024-01-05 07:57 UTC, senghe commented on tests/Integration/Repository/DraftImageRepositoryTest.php
> +class DraftImageRepositoryTest extends JsonApiTestCase
```suggestion
final class DraftImageRepositoryTest extends JsonApiTestCase
```

2024-01-05 07:57 UTC, senghe commented on features/vendor/vendor_can_remove_product_lisitng_image.feature
> +    And I click "Save draft" button
This is not Then

2024-01-05 07:57 UTC, senghe commented on features/vendor/vendor_can_remove_product_lisitng_image.feature
> +    And I follow "Edit"
This is When

2024-01-05 07:57 UTC, senghe commented on features/vendor/create_product_listing_without_price.feature
>      And I follow "Product listings"
This is When

2024-01-05 07:57 UTC, senghe commented on src/Component/ProductListing/ListingPersister.php
> +    public function deleteImages(DraftInterface $productDraft): void
This class should be specced.

2024-01-08 12:11 UTC, senghe requested changes

2024-01-08 12:11 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +class ListingPersisterSpec extends ObjectBehavior
final :pray:

2024-01-08 12:11 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +    public function it_resolve_latest_draft(
```suggestion
    public function it_resolves_latest_draft(
```

2024-01-08 12:11 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +    public function it_update_latest_draft_with(
```suggestion
    public function it_updates_latest_draft_with(
```

2024-01-08 12:11 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +    public function it_upload_images(
```suggestion
    public function it_uploads_images(
```

2024-01-08 12:11 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +    public function it_vendor_can_not_delete_images_that_not_exist(
This is not a correct sentence

2024-01-08 12:11 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +    public function it_vendor_can_not_delete_images_with_incorrect_path(
It is not correct sentence

2024-01-08 12:11 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +        $productDraft->getCode()->willReturn('ABC123');
Please use better string constants. If it's product code, better would be to use `mug`

2024-01-08 12:11 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +        $this->uploadImages($productDraft);
I do not get what the test here does. There is no verification what has been done. Additionally we've two methods running on the test. Is that correct?

2024-01-09 18:50 UTC, senghe requested changes

2024-01-09 18:50 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +        $draftGenerator->generateNextDraft($productListing)->shouldBeCalledOnce();
```suggestion
        $draftGenerator->generateNextDraft($productListing)->willReturn($productDraft);
        
        $this->resolveLatestDraft($productListing);
```

2024-01-09 18:50 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +        $imageUploader->upload($image)->shouldBeCalledOnce();
```suggestion
        $draftGenerator->generateNextDraft($productListing)->willReturn($productDraft);
        $imageUploader->upload($image)->shouldBeCalledOnce();
        
        $this->uploadImages($productDraft);
```

2024-01-09 18:50 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +        $filesystem->delete($path)->shouldBeCalled();
Why in one place we have "Should have" but in other similar we have "Should be"? Additionally, the "Should be" thingies should be placed before line of deleting images.

2024-01-09 18:50 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +        $filesystem->delete($path)->shouldBeCalled();
Please correct this for all cases below.

2024-01-09 18:50 UTC, senghe commented on tests/Behat/Context/Ui/Vendor/ProductListingContext.php
> +        $this->createProudctListinByVendor($count, $status);
A typo

2024-01-09 18:50 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +    public function it_can_not_delete_images_that_not_exist(
```suggestion
    public function it_can_not_delete_images_that_do_not_exist(
```

2024-01-09 18:50 UTC, senghe commented on spec/Component/ProductListing/ListingPersisterSpec.php
> +    public function it_updates_latest_draft_with(
```suggestion
    public function it_updates_latest_draft(
```

With what? :thinking:

2024-01-24 20:09 UTC, senghe approved these changes
I'm approving this in advance. But please fix the typos :pray:

2024-01-24 20:09 UTC, senghe commented on tests/Behat/Context/Ui/Vendor/ProductListingContext.php
> +        $page = $this->getPage();
The `getPage()` method shouldn't exist. We should create a separate page class for this. But I know you've just copied and pasted this. So let's stay with this as is.

2024-01-24 20:09 UTC, senghe commented on tests/Behat/Context/Ui/Vendor/ProductListingContext.php
> +        $this->createProudctListingByVendor($count);
Still the typo :vulcan_salute:

2024-01-24 20:09 UTC, senghe commented on tests/Behat/Context/Ui/Vendor/ProductListingContext.php
> +        $this->createProudctListingByVendor($count, $status);
Still the typo :)

2024-01-31 09:42 UTC, merged