[MUL-306] extend draft with tax category
BitBagCommerce/OpenMarketplace pull request #156
Opened 2024-01-15 09:15 UTC by Kriz83

2024-01-19 12:01 UTC, senghe requested changes

2024-01-19 12:01 UTC, senghe commented on translations/messages.en.yml
> +        tax_category: Tax Category
```suggestion
        tax_category: Tax category
```

2024-01-19 12:01 UTC, senghe commented on features/vendor/create_product_listing_with_tax_category.feature
> +@vendor_managing_product_listings
We discussed on the call to refactor the scenarios

2024-01-22 19:31 UTC, senghe requested changes

2024-01-22 19:31 UTC, senghe commented on tests/Behat/Context/Setup/ProductListingContext.php
> +//        $this->entityManager->flush();
```suggestion
```

2024-01-22 19:31 UTC, senghe commented on tests/Behat/Context/Setup/ProductListingContext.php
> +        $this->getSession()
We should create separate page class for this (please see the `test/Behat/Page` directory)

2024-01-22 19:31 UTC, senghe commented on tests/Behat/Context/Ui/Vendor/ProductListingContext.php
> +        $rows = $this->getPage()->findAll('css', 'table > tbody > tr');
We should use separate page class for this.

2024-01-23 08:06 UTC, Kriz83 commented on features/vendor/create_product_listing_with_tax_category.feature
> +@vendor_managing_product_listings
done

2024-01-23 08:17 UTC, senghe approved these changes

2024-01-23 08:29 UTC, merged