[Mul-316] breadcrumbs and titles unify
BitBagCommerce/OpenMarketplace pull request #166
Opened 2024-01-24 08:19 UTC by Kriz83

Change breadcrumbs generation process for vendor account parts, change and fix incorrect or inconsistent titles

2024-01-26 09:48 UTC, senghe requested changes

2024-01-26 09:48 UTC, senghe commented on src/Component/Core/Api/Resources/api_resources/ProductVariant.xml
>              <itemOperation name="vendor_inventory_get">
This file cannot be changed

2024-01-26 09:48 UTC, senghe commented on src/Component/Core/Api/Resources/serialization/ProductVariant.xml
>      <class name="Sylius\Component\Core\Model\ProductVariant">
This file also shouldn't be changed

2024-01-26 09:48 UTC, senghe commented on src/Component/Core/Vendor/Twig/Extension/BreadcrumbExtension.php
> +            'active' => $activeValue,
```suggestion
            'translation' => $translatable,
            'activeValue' => $activeValue,
```

2024-01-26 09:48 UTC, senghe commented on src/Component/Core/Vendor/Twig/Extension/BreadcrumbExtension.php
> +declare(strict_types=1);
I asked @Kriz83 on a call to use the strategy pattern for this. The _generatedBreadcrumb.html.twig file can stay.

2024-01-26 09:48 UTC, senghe commented on templates/Context/Vendor/Settlement/create.html.twig
> +    {% include 'Context/Vendor/Common/_generatedBreadcrumb.html.twig' %}
```suggestion
    {% include 'Context/Vendor/Common/_generatedBreadcrumb.html.twig' with {"context": "settlement-create"} %}
```

2024-01-31 11:14 UTC, Kriz83 commented on src/Component/Core/Vendor/Twig/Extension/BreadcrumbExtension.php
> +declare(strict_types=1);
it is now

2024-02-06 20:09 UTC, senghe approved these changes

2024-02-07 06:29 UTC, BartoszWojdalowicz approved these changes

2024-02-07 08:13 UTC, merged