MUL 151 Add support for inventory management by API
BitBagCommerce/OpenMarketplace pull request #24
Opened 2023-02-16 14:42 UTC by Wojdylak

2023-02-23 11:41 UTC, senghe requested changes

2023-02-23 11:41 UTC, senghe commented on spec/Api/SectionResolver/ShopVendorApiUriBasedSectionResolverSpec.php
> +    public function it_throws_an_exception_if_path_does_not_start_with_api_v2_shop_vendor(): void
I think you should split this into separate specs

2023-02-23 11:41 UTC, senghe commented on src/Api/Doctrine/ProductVariantCurrentVendorExtension.php
> +        private VendorContextInterface $vendorContext,
I think we should use older method for code-style consistency

2023-02-23 11:41 UTC, senghe commented on src/Api/Doctrine/VendorAwareExtension.php
> +        private VendorContextInterface $vendorContext,
Consistency first! :)

2023-02-23 11:41 UTC, senghe commented on src/Api/Doctrine/VendorAwareExtension.php
> +        private VendorContextInterface $vendorContext,
And it probably will be removed :upside_down_face:

2023-02-23 11:41 UTC, senghe commented on src/Api/SectionResolver/ShopVendorApiUriBasedSectionResolver.php
> +    public function __construct(private string $shopVendorApiUriBeginning)
Consistency :)

2023-02-23 11:41 UTC, senghe commented on src/Api/SectionResolver/ShopVendorApiUriBasedSectionResolver.php
> +        return new ShopVendorApiSection();
We should use factory here

2023-02-23 11:41 UTC, senghe commented on src/Api/Serializer/ProductVariantNormalizer.php
> +        private ContextAwareNormalizerInterface $productVariantNormalizer,
Could you check this globally? :thinking:

2023-02-23 11:41 UTC, senghe commented on src/Resources/config/serialization/ProductVariant.xml
> +    <class name="Sylius\Component\Core\Model\ProductVariant">
How about using parameter instead of hardcoded name?

2023-02-23 12:30 UTC, Wojdylak commented on src/Api/Doctrine/VendorAwareExtension.php
> +        private VendorContextInterface $vendorContext,
In the next PR

2023-02-23 12:57 UTC, Wojdylak commented on src/Resources/config/serialization/ProductVariant.xml
> +    <class name="Sylius\Component\Core\Model\ProductVariant">
I checked. When we use parameter, the object does not serialize

2023-03-07 07:42 UTC, senghe commented on src/Factory/ShopVendorApiSectionFactoryInterface.php
> +declare(strict_types=1);
No OS header :)

2023-03-07 07:42 UTC, senghe commented on src/Factory/ShopVendorApiSectionFactoryInterface.php
> +<?php
```suggestion
<?php


/*
 * This file was created by developers working at BitBag
 * Do you need more information about us and what we do? Visit our https://bitbag.io website!
 * We are hiring developers from all over the world. Join us and start your new, exciting adventure and become part of us: https://bitbag.io/career
*/
```

2023-03-07 07:43 UTC, senghe approved these changes

2023-03-08 11:53 UTC, merged