Mul 209 payment status update for secondary orders
BitBagCommerce/OpenMarketplace pull request #59
Opened 2023-03-14 07:54 UTC by MacBalc

2023-03-14 08:06 UTC, rafalmal approved these changes

2023-03-14 08:07 UTC, rafalmal requested changes

2023-03-14 08:07 UTC, rafalmal commented on tests/Behat/Context/Shop/OrderContext.php
> +        ) {
this is incorrect

2023-03-14 08:09 UTC, rafalmal requested changes

2023-03-14 08:09 UTC, rafalmal commented on tests/Behat/Context/Shop/OrderContext.php
> +        foreach ($labels as $label){
```suggestion
        foreach ($labels as $label) {
```

2023-03-14 09:45 UTC, MacBalc commented on tests/Behat/Context/Shop/OrderContext.php
> +        ) {
done

2023-03-14 10:31 UTC, rafalmal approved these changes

2023-04-21 06:53 UTC, Wojdylak commented on tests/Behat/Context/Shop/OrderContext.php
> +        $labels = $page->findAll('css', '.ui.green.label');
Why only `green`?

2023-04-21 07:12 UTC, rafalmal commented on tests/Behat/Context/Shop/OrderContext.php
> +        $labels = $page->findAll('css', '.ui.green.label');
I check only for green labeled "complete" or "fullfilled" orders, but extended flexibility of this method in next commit.

2023-05-15 18:32 UTC, merged