MUL-238/Fix vendor form
BitBagCommerce/OpenMarketplace pull request #80
Opened 2023-04-20 09:34 UTC by rafalmal

2023-04-20 09:38 UTC, PiotrSzymanski2000 approved these changes

2023-04-20 09:41 UTC, mpysiak requested changes

2023-04-20 09:41 UTC, mpysiak commented on src/Form/Type/VendorType.php
>      public function __construct(
do we need __contruct() now?

2023-04-20 09:44 UTC, rafalmal commented on src/Form/Type/VendorType.php
>      public function __construct(
Good point, its not needed now, removed in next commit

2023-04-20 09:55 UTC, mpysiak approved these changes

2023-05-15 12:49 UTC, senghe approved these changes

2023-05-15 12:49 UTC, merged