Mul 230/vendor page
BitBagCommerce/OpenMarketplace pull request #82
Opened 2023-04-28 04:54 UTC by rafalmal

2023-05-09 08:22 UTC, senghe requested changes

2023-05-09 08:22 UTC, senghe commented on src/Provider/TaxonProvider.php
> +    public function provideForVendorPage(?string $slug, string $locale): ?TaxonInterface
It has no integration tests. Additionally, the query builder part has to be put into repository.

2023-05-09 08:22 UTC, senghe commented on src/Repository/ProductRepository.php
> +        ): QueryBuilder {
Formattings

2023-05-09 08:22 UTC, senghe commented on src/Repository/ProductRepository.php
> -            ->setParameter('vendor', $vendor)
Removing all the code here won't break any other functionality, will it?

2023-05-09 08:22 UTC, senghe commented on src/Repository/ProductRepositoryInterface.php
> +        ): QueryBuilder;
Formatting

2023-05-09 08:22 UTC, senghe commented on src/Resources/config/doctrine/VendorBackgroundImage.orm.xml
> +            <join-column name="owner_id" referenced-column-name="id" nullable="false" on-delete="CASCADE" />
I think I would write a test for removing vendor's image, to prove it won't remove the owners entity.

2023-05-09 08:22 UTC, senghe commented on src/Resources/config/grids/shop/sylius_shop_vendor_product.yml
> +          type: string 
What's the square character?

2023-05-09 08:22 UTC, senghe commented on src/Resources/config/grids/shop/sylius_shop_vendor_product.yml
> +          type: string 
The square

2023-05-09 08:22 UTC, senghe commented on src/Resources/config/resources/product.yml
> +      classes:
If we added new method to model, we should also add it's interface.

2023-05-09 08:22 UTC, senghe commented on src/Resources/config/api_resources/VendorBackgroundImage.xml
> +<resources xmlns="https://api-platform.com/schema/metadata"
Do we have any tests for this?

2023-05-09 08:22 UTC, senghe commented on src/Twig/VendorExtension.php
> +    private TaxonRepository $taxonRepository;
Interface :pray:

2023-05-09 08:22 UTC, senghe commented on src/Twig/VendorExtension.php
> +    public function getMainTaxon(): TaxonInterface
I would add the $channel parameter, as we could have multiple channels, and each of them can have different main taxon.

2023-05-09 08:22 UTC, senghe commented on templates/Vendor/vendor_page.html.twig
> +                                {% set acceptedReviews = acceptedReviews + 1 %}
I wouldn't calculate this here. I would put this logic into entity.

2023-05-09 08:22 UTC, senghe commented on templates/Vendor/vendor_page.html.twig
> +                            {% set productsAvarageRating = productsAvarageRating + product.averageRating|round(2) %}
I would put the logic into entity.

2023-05-09 08:22 UTC, senghe commented on tests/Behat/Context/Vendor/VendorUpdateContext.php
> +    private TaxonFactory $taxonFactory;
Interface :pray:

2023-05-09 08:22 UTC, senghe commented on tests/Behat/Context/Vendor/VendorUpdateContext.php
> +        $taxon->enable();
We should attach the taxon into channel. I don't see it here. Does it exist in different place? If so, why the @Given tells anything about channel?

2023-05-09 08:22 UTC, senghe commented on tests/Integration/DataFixtures/ORM/VendorRepositoryTest/test_it_finds_correct_vendor.yml
> +
```suggestion
```

2023-05-09 08:22 UTC, senghe commented on tests/Integration/Repository/ProductRepositoryTest.php
> +<?php
No OS header

2023-05-09 08:22 UTC, senghe commented on tests/Integration/Repository/ProductRepositoryTest.php
> +class ProductRepositoryTest extends JsonApiTestCase
Can it be final?

2023-05-09 08:22 UTC, senghe commented on tests/Integration/Repository/VendorRepositoryTest.php
> +<?php
Missing OS header

2023-05-09 08:22 UTC, senghe commented on tests/Integration/Repository/VendorRepositoryTest.php
> +    public function test_it_finds_correct_vendor(): void
Too little scenarios (null scenario is missing).

2023-05-09 08:22 UTC, senghe commented on tests/Integration/Repository/VendorRepositoryTest.php
> +class VendorRepositoryTest extends JsonApiTestCase
Can it be final?

2023-05-09 08:37 UTC, rafalmal commented on features/vendor/vendor_can_update_profile.feature
> +    Given There is pending update data with token value "simpletoken" for logged in vendor
I dont understand i just removed space at the end here

2023-05-09 08:44 UTC, rafalmal commented on tests/Integration/Repository/ProductRepositoryTest.php
> +class ProductRepositoryTest extends JsonApiTestCase
Added final statement in next commit.

2023-05-09 08:44 UTC, rafalmal commented on tests/Integration/Repository/VendorRepositoryTest.php
> +class VendorRepositoryTest extends JsonApiTestCase
Added final statement in next commit.

2023-05-09 08:45 UTC, rafalmal commented on src/Provider/TaxonProvider.php
> +final class TaxonProvider
Added interface.

2023-05-09 08:45 UTC, rafalmal commented on src/Provider/TaxonProvider.php
> +<?php
Added OS header.

2023-05-09 08:59 UTC, rafalmal commented on features/vendor/vendor_can_update_profile.feature
> +    And the channel has as a menu taxon
FIxed typo in next commit.

2023-05-09 09:00 UTC, rafalmal commented on src/Operator/VendorBackgroundOperator.php
> +    public function __construct(EntityManagerInterface $entityManager, VendorBackgroundImageFactoryInterface $vendorBackgroundImageFactory)
Fixed in next commit.

2023-05-09 11:10 UTC, rafalmal commented on tests/Behat/Context/Vendor/VendorUpdateContext.php
> +    private TaxonFactory $taxonFactory;
Done in next commit.

2023-05-09 12:36 UTC, rafalmal commented on src/Twig/VendorExtension.php
> +    private TaxonRepository $taxonRepository;
Replaced with interface.

2023-05-09 16:41 UTC, rafalmal commented on src/Resources/config/grids/shop/sylius_shop_vendor_product.yml
> +          type: string 
Removed

2023-05-10 04:58 UTC, rafalmal commented on tests/Integration/Repository/VendorRepositoryTest.php
> +<?php
OS header added.

2023-05-10 05:06 UTC, rafalmal commented on src/Repository/ProductRepository.php
> -            ->setParameter('vendor', $vendor)
no replacing method reateListQueryBuilder with createShopListQueryBuilder covers this functionality.

2023-05-10 05:06 UTC, rafalmal commented on tests/Integration/Repository/ProductRepositoryTest.php
> +<?php
OS header added

2023-05-10 05:07 UTC, rafalmal commented on templates/Vendor/vendor_page.html.twig
> +                                {% set acceptedReviews = acceptedReviews + 1 %}
Moved this logic to entity.

2023-05-10 05:07 UTC, rafalmal commented on templates/Vendor/vendor_page.html.twig
> +                            {% set productsAvarageRating = productsAvarageRating + product.averageRating|round(2) %}
Moved this logic to entity.

2023-05-10 05:16 UTC, rafalmal commented on tests/Integration/Repository/VendorRepositoryTest.php
> +    public function test_it_finds_correct_vendor(): void
Added test scenario.

2023-05-10 08:42 UTC, rafalmal commented on features/shop/vendor_page.feature
> +Feature: Displaying vendor page
Added scenarios.

2023-05-10 10:59 UTC, rafalmal commented on src/Repository/ProductRepositoryInterface.php
> +        ): QueryBuilder;
Fixed

2023-05-10 10:59 UTC, rafalmal commented on src/Resources/config/doctrine/VendorBackgroundImage.orm.xml
> +            <join-column name="owner_id" referenced-column-name="id" nullable="false" on-delete="CASCADE" />
Added test for this case.

2023-05-10 10:59 UTC, rafalmal commented on src/Resources/config/api_resources/VendorBackgroundImage.xml
> +<resources xmlns="https://api-platform.com/schema/metadata"
Added tests.

2023-05-17 20:24 UTC, merged