Feature/mul 211 primary order hiding
BitBagCommerce/OpenMarketplace pull request #83
Opened 2023-04-28 05:42 UTC by MacBalc

2023-05-08 20:35 UTC, senghe requested changes

2023-05-08 20:35 UTC, senghe commented on src/Repository/OrderRepository.php
> +
The methods below are not related to the production code. I would create separate repository for this on `tests/Behat` namespace.

2023-05-08 20:35 UTC, senghe commented on src/Repository/OrderRepository.php
> +            ->andWhere('o.mode = :secondaryOrderMode')
Do we have any test for this?

2023-05-08 20:35 UTC, senghe commented on src/Repository/OrderRepository.php
> +    public function findAllSecondaryOrders(): QueryBuilder
Do we have any test for this?

2023-05-08 20:35 UTC, senghe commented on features/admin/customer_orders.feature
> +  viewing the list of orders for a specific customer
```suggestion
  During orders list view for a specific customer
```

2023-05-08 20:35 UTC, senghe commented on features/shop/order.feature
> +    Then I should see 3 orders
I would put the order numbers as parameter. to prove the orders are correct.

2023-05-08 20:35 UTC, senghe commented on src/Repository/OrderRepository.php
> +    public function findLatestInChannel(int $count, ChannelInterface $channel): array
Unused method

2023-05-08 20:35 UTC, senghe commented on src/Repository/OrderRepository.php
> +    public function countPaidByChannel(ChannelInterface $channel): int
Unused method

2023-05-08 20:35 UTC, senghe commented on src/Repository/OrderRepository.php
> +    public function createByCustomerIdQueryBuilder($customerId): QueryBuilder
Unused method

2023-05-08 20:35 UTC, senghe commented on src/Repository/OrderRepository.php
> +    /** @phpstan-ignore-next-line */
Additionally, when you make line-ignore, please tell us, why you do it (in a comment)

2023-05-08 20:35 UTC, senghe commented on src/Repository/PaymentRepository.php
> +    public function findPaymentsOfSecondaryOrders(): QueryBuilder
Incorrect method name. It does not find. It returns query builder for secondary order payments.

2023-05-08 20:35 UTC, senghe commented on features/admin/payment_viewing.feature
> +  i should not see primary order payments
```suggestion
  I should not see primary order payments
```

2023-05-08 20:35 UTC, senghe commented on spec/NumberAssigner/OrderNumberAssignerSpec.php
> +        $this->shouldImplement(\BitBag\OpenMarketplace\NumberAssigner\OrderNumberAssignerInterface::class);
Missing import statement

2023-05-08 20:35 UTC, senghe commented on src/Repository/ShipmentRepository.php
> +    public function findShipmentsWithoutPrimaryModeOrder(): QueryBuilder
Incorrect method name

2023-05-08 20:35 UTC, senghe commented on features/admin/customer_orders.feature
> +    Then I should see 1 orders
Where is the information, it's not the primary order?

2023-05-08 20:35 UTC, senghe commented on features/admin/payment_viewing.feature
> +    Then I should see 1 payments
Where is the information, it's not the payment for primary order?

2023-05-08 20:35 UTC, senghe commented on features/admin/shipment_viewing.feature
> +    Then I should see 1 shipments
Where is the information, it's not the shipment for primary order?

2023-05-08 20:35 UTC, senghe commented on features/admin/customer_orders.feature
> +@hiding_primary_orders_in_customer_tab
In all behat scenarios I don't see any information (given?), how many orders we have, and which is secondary, and which is primary. When non-tech person reads the .feature file, they should be able to analyse the scenario. Currently I can't.

2023-05-09 05:28 UTC, MacBalc commented on src/Repository/OrderRepository.php
> +
Methods below line 84 overwrite methods that are used to calculate dashboard statistics.

2023-05-09 08:08 UTC, MacBalc commented on src/Repository/OrderRepository.php
> +            ->andWhere('o.mode = :secondaryOrderMode')
Test added

2023-05-09 08:08 UTC, MacBalc commented on src/Repository/OrderRepository.php
> +    public function findAllSecondaryOrders(): QueryBuilder
Test added

2023-05-09 08:09 UTC, MacBalc commented on features/admin/customer_orders.feature
> +  viewing the list of orders for a specific customer
Change applied

2023-05-09 08:10 UTC, MacBalc commented on features/shop/order.feature
> +    Then I should see 3 orders
I have changed logic to make sure that displayed orders are not primary

2023-05-09 08:15 UTC, MacBalc commented on src/Repository/ShipmentRepository.php
> +    public function findShipmentsWithoutPrimaryModeOrder(): QueryBuilder
Name changed

2023-05-09 08:16 UTC, MacBalc commented on features/admin/customer_orders.feature
> +    Then I should see 1 orders
I have changed logic to make sure that displayed orders are not primary

2023-05-09 08:16 UTC, MacBalc commented on features/admin/payment_viewing.feature
> +    Then I should see 1 payments
I have changed logic to make sure that displayed orders are not primary

2023-05-09 08:16 UTC, MacBalc commented on features/admin/shipment_viewing.feature
> +    Then I should see 1 shipments
I have changed logic to make sure that displayed orders are not primary

2023-05-09 08:16 UTC, MacBalc commented on features/admin/customer_orders.feature
> +@hiding_primary_orders_in_customer_tab
I have changed logic to make sure that displayed orders are not primary

2023-05-09 09:31 UTC, MacBalc commented on src/Repository/OrderRepository.php
> +    public function createByCustomerIdQueryBuilder($customerId): QueryBuilder
Methods below line 84 overwrite methods that are used to calculate dashboard statistics.

2023-05-09 09:53 UTC, MacBalc commented on src/Repository/OrderRepository.php
> +    /** @phpstan-ignore-next-line */
Comment added

2023-05-09 09:53 UTC, MacBalc commented on src/Repository/PaymentRepository.php
> +    public function findPaymentsOfSecondaryOrders(): QueryBuilder
Name changed

2023-05-09 09:53 UTC, MacBalc commented on features/admin/payment_viewing.feature
> +  i should not see primary order payments
Change applied

2023-05-09 09:53 UTC, MacBalc commented on spec/NumberAssigner/OrderNumberAssignerSpec.php
> +        $this->shouldImplement(\BitBag\OpenMarketplace\NumberAssigner\OrderNumberAssignerInterface::class);
Import added

2023-05-22 09:46 UTC, merged